version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"

