apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservices.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ include "microservices.fullname" . }}-user-service
            port:
              number: 80
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: {{ include "microservices.fullname" . }}-product-service
            port:
              number: 80
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: {{ include "microservices.fullname" . }}-order-service
            port:
              number: 80

